[package]
name = "libp2p-multilang"
version = "0.1.0"
authors = ["folex"]
edition = "2018"

[dependencies]
futures = "0.1"
libp2p = "0.13.1"
libp2p-core = "0.13.1"
libp2p-ping = "0.13.1"
libp2p-swarm = "0.3.0"

void = "1.0.2"
names = "0.11"
tokio = "0.1"
tokio-stdin-stdout = "0.1"

env_logger = "0.7.1"

base64 = "0.11.0"